### ISSUE TITLE
Host your model needs to be renamed in nav 

### ISSUE THREAD

**Issue by StephanieKim** [algorithmiaio/dev-center#149]
"Host your model" is vague and needs to be more clear. Thoughts are "ML Framework Guides", "AI Model Hosting", etc. Open to suggestions but should represent that we support hosting your machine learning/deep learning model in various frameworks.

**Comment by JamesHoover** [comment]
I vote for "AI Model Hosting" thats more of the language we are moving towards or including ML to be "AI/ML Model Hosting"

**Comment by zeryx** [comment]
We were thinking that "model" might be a bit of a logic leap that might be more difficult for some. Framework or Library is common lingo in every type of software dev circle, and since we're targetting people from a wide range it makes sense to keep it somewhat jargon-free - especially in the self-help areas.

**Comment by JamesHoover** [comment]
interesting, yeah if you think "framework" is more appropriate lets go with that. Part of the thing we wanted to get across is that we host. so does something like "framework hosting" make sense?

**Comment by StephanieKim** [comment]
Let's think through this. These are guides to host your own model using one of our supported machine and deep learning frameworks. Somehow we need to condense that lol.

**Comment by zeryx** [comment]
Yea I think we might be able to split them up here, we can have a "how to host your model" as a general purpose post (since for the most part, it's standard boilerplate in our docs) which is mostly just into to data API stuff, and then we can have framework specific docs. What are your thoughts on that direction?

**Comment by MikeyAnderson** [comment]
It’s an A/B test

Sent from my iPhone

Mike Anderson

**Comment by besirkurtulmus** [comment]
How about "Deploy your model"? It speaks to both developers and big organizations.

**Comment by StephanieKim** [comment]
Going to go with Besir's suggestion for changing nav item
