### ISSUE TITLE
Users confused about permission settings and gpu flag

### ISSUE THREAD

**Issue by doppenhe** [algorithmiaio/dev-center#16]
http://developers.algorithmia.com/algorithm-development/model-guides/caffe/

User error but we should update screenshot to have GPU and all permissions open by default. People dont read then they hit basic errors when getting started.  In this case customer was redfin.

**Comment by anowell** [comment]
if by "open" you mean "nothing selected": 👍 

if you mean we should default to very "open" settings (enable internet, recursive, and GPU by default): 👎

**Comment by doppenhe** [comment]
the caffe guide should have GPU selected by default because thats what loads the special docker image.

on the permissions side. The first thing people do is send an image to these classifiers. usually a URL which fails with an uncomprehensive error. Bad security practice but even worse experience...

**Comment by anowell** [comment]
oh.. I didn't realize you were just asking for an updated screenshot. very obvious now that I reread it. :shamecube:

**Comment by doppenhe** [comment]
👍

**Comment by Argoday** [comment]
:+1: screenshots should match instructions, though:

The algorithm should be able to detect GPU / no-GPU slot type options in order to provide proper user error messages. That can easily be added by both creating an inspection route to anode and an options field to the Request object (see the stdin/stdout spec).

In the short term: errors are already scanned by regexes to replace bad error messages with better ones - you should argument that list to include these about no-GPU and return a warning back with the error (see api-v1 spec, looks like it was stripped from the docs) or swap the error.message directly

**Comment by StephanieKim** [comment]
Note to self: have all three permission settings selected for DL models and create a separate screenshot for non-DL models to have first two options selected.

**Comment by StephanieKim** [comment]
Changed screenshots
