### ISSUE TITLE
CLI build failing

### ISSUE THREAD

**Issue by doppenhe** [algorithmiaio/dev-center#77]
![capture](https://cloud.githubusercontent.com/assets/2166701/22681266/21fae79c-ecc1-11e6-878a-9a7cd7f17391.PNG)

**Comment by anowell** [comment]
bahaha.. this is using the default travis badge for the CLI.. and while I should fix the build (I made changes that depended on unstable rust until last week - and was just about to push a fix anyway), we should just completely remove the badge so that future broken builds don't show this icon in the devcenter.

**Comment by StephanieKim** [comment]
I think only CLI and cURL might show that - none of the other dev center guides will have this badge so yeah that should be removed anyway. Note that CLI and cURL guides weren't updated the same as the others.

**Comment by StephanieKim** [comment]
Pushed a commit to fix this - will be on next build

**Comment by anowell** [comment]
published.
