### ISSUE TITLE
Page weight

### ISSUE THREAD

**Issue by platypii** [algorithmiaio/dev-center#95]
Dev center landing page is way too big in file size:

over 2mb just for:
deepfilter-fb.png, analyze-tweets-algorithms-fb.jpg, get_started.png

**Comment by anowell** [comment]
[These snippets](https://github.com/algorithmiaio/dev-center/blob/579410f6eaf4f012ed88af2fb2e2bb8ddd3cf55c/index.html#L84-L90) invoke a plugin that fetches the metadata for the blog page, and downloads a copy of the blog article's main image (to serve it securely now that the devcenter lives in https land). 

So shrinking these involves adding some ruby lib to programmatically downsize these files [here](https://github.com/algorithmiaio/dev-center/blob/master/_plugins/socialcard.rb#L56-L59)

**Comment by platypii** [comment]
Ah, I see now. Looks like it would be pretty easy ruby to write, but I can see why that was skipped.

Could probably get substantial improvement if we just switched deepfilter-fb.png (1.5mb) to a jpg (or a squished png at least)

**Comment by peckjon** [comment]
For now, you want me to just run these through tinypng.com?  Their lossless compression beats most every library I've tried.

**Comment by anowell** [comment]
those images aren't checked in.. they are downloaded directly to jekyll's
build output directory, and would get blown away on every deploy
(especially after I fix the continuous deploy via CodeDeploy via shippable
tomorrow. Rather than hack around that, I'd rather just add a build
dependency on [minimagick](https://github.com/minimagick/minimagick) or
similar, and have it resize the image.

This keeps the workflow really nice for allowing these "featured articles"
to be rotated out as often as our content gurus would like.
 I :heart: automated workflows.

-Anthony

**Comment by anowell** [comment]
That change brings the combined sizes down to about ~415k for the current featured blog posts...
