### ISSUE TITLE
Clean up some language of algorithm developer guides

### ISSUE THREAD

**Issue by StephanieKim** [algorithmiaio/dev-center#96]
**Add:**
This path is based on your Algorithmia user name and the name of your algorithm, so if you are “demo” and your algorithm is “TokenizeText”, then the path for version 0.1.1 of your algorithm will be demo/TokenizeText/0.1.1
**To:** 
I/O section see JavaScript guide for where

**Clean up:**
Working with Data Stored on Algorithmia section portion where it talks about what the code is doing. **Current content isn't super clear:**
"This example shows how to create an algorithm that takes a user’s file stored in a data collection on the Algorithmia platform and splits up the text into sentences and then splits those sentences up into words:"
**Change to something clearer**

**Comment by peckjon** [comment]
"This example shows how to create an algorithm that extracts text from a file and breaks it up into individual words.  Instead of sending the file itself, the user will provide the pathname of a file they have already uploaded to their [Hosted Data](https://algorithmia.com/developers/data/hosted/), in the form "data://YOUR_USERNAME/DATA_COLLECTION_NAME/filename.txt".  They could also use a [Dropbox](https://algorithmia.com/developers/data/dropbox) or [S3](https://algorithmia.com/developers/data/s3) file path.
